apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: baserow
    component: baserow-backend
  name: baserow-backend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: baserow-backend:latest
  selector:
    app: baserow-backend
    deploymentconfig: baserow-web-frontend
  source:
    dockerfile: |
      WORKDIR /backend
      RUN git clone https://github.com/derekroberts/baserow.git /tmp/baserow && \
          cp -rT /tmp/baserow/backend/* . && \
          rm -rf /tmp/baserow && \
          chmod -R 777 .

      ENV PYTHONPATH $PYTHONPATH:/backend/src
      ENV DJANGO_SETTINGS_MODULE='baserow.config.settings.dev'

      RUN apt-get update
      RUN apt-get -y install make gnupg2

      RUN make install-dependencies

      CMD tail -f /dev/null

    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: python:3.6
    type: Docker
  triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
