---
apiVersion: v1
kind: Template
metadata:
  name: ${APP}-${COMPONENT}
labels:
  app: ${APP}
  component: ${COMPONENT}
parameters:
  - name: APP
    value: baserow
  - name: COMPONENT
    value: backend
  - name: IMG_TAG
    value: latest
  - name: APP_PORT
    value: "8000"
  - name: APP_NAMESPACE
    value: csnr-devops-lab-deploy
  - name: WEB_FRONTEND_NAMESPACE
    value: csnr-devops-lab-deploy
  - name: WEB_FRONTEND_COMPONENT
    value: web-frontend
  - name: DOMAIN
    value: pathfinder.gov.bc.ca
  - name: DATABASE_COMPONENT
    value: database
  - name: MJML_COMPONENT
    value: mjml
  - name: SRC_GIT_URL
    value: https://gitlab.com/bramw/baserow.git
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      replicas: 1
      selector:
        app: ${APP}
        component: ${COMPONENT}
      strategy:
        resources: {}
        type: Recreate
        recreateParams:
          timeoutSeconds: 900
          mid:
            failurePolicy: Abort
            execNewPod:
              command:
                - "python"
                - "/backend/src/baserow/manage.py"
                - "migrate"
            containerName: ${APP}-${COMPONENT}-migrate
        activeDeadlineSeconds: 21600
      template:
        metadata:
          labels:
            app: ${APP}
            component: ${COMPONENT}
        spec:
          containers:
            - env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: ${APP}-${DATABASE_COMPONENT}
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: ${APP}-${DATABASE_COMPONENT}
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: ${APP}-${DATABASE_COMPONENT}
                - name: DATABASE_HOST
                  value: ${APP}-${DATABASE_COMPONENT}
                - name: MJML_SERVER_HOST
                  value: ${APP}-${MJML_COMPONENT}
                - name: PUBLIC_WEB_FRONTEND_URL
                  value: https://${APP}-${WEB_FRONTEND_COMPONENT}-${WEB_FRONTEND_NAMESPACE}.${DOMAIN}
                - name: PUBLIC_BACKEND_URL
                  value: https://${APP}-${COMPONENT}-${APP_NAMESPACE}.${DOMAIN}
                - name: PRIVATE_BACKEND_URL
                  value: http://${APP}-${COMPONENT}:${APP_PORT}
              image: " "
              name: ${APP}-${COMPONENT}
              ports:
                - containerPort: ${{APP_PORT}}
          restartPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP}-${COMPONENT}
            from:
              kind: ImageStreamTag
              name: ${APP}-${COMPONENT}:${IMG_TAG}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      ports:
        - name: ${APP_PORT}
          port: ${{APP_PORT}}
      selector:
        app: ${APP}
        component: ${COMPONENT}
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      host: ${APP}-${COMPONENT}-${APP_NAMESPACE}.${DOMAIN}
      port:
        targetPort: ${{APP_PORT}}
      to:
        kind: Service
        name: ${APP}-${COMPONENT}
      tls:
        termination: edge
