apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: baserow
    component: baserow-backend
  name: baserow-backend
spec:
  replicas: 1
  selector:
    app: baserow
    deploymentconfig: baserow-backend
  strategy:
    resources: {}
    type: Recreate
    recreateParams:
      timeoutSeconds: 900
      mid:
        failurePolicy: Abort
        execNewPod:
          command:
            - "python"
            - "/backend/src/baserow/manage.py"
            - "migrate"
        containerName: baserow-backend-migrate
        env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: baserow-db
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: baserow-db
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: baserow-db
          - name: DATABASE_HOST
            value: baserow-db
    resources: {}
    activeDeadlineSeconds: 21600
  template:
    metadata:
      labels:
        app: baserow
        deploymentconfig: baserow-backend
    spec:
      containers:
        - env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: baserow-db
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: baserow-db
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: baserow-db
            - name: DATABASE_HOST
              value: baserow-db
          image: ' '
          name: baserow-backend
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - baserow-backend
        from:
          kind: ImageStreamTag
          name: baserow-backend:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
