apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: baserow-backend-claim0
    app: baserow
    app.kubernetes.io/part-of: baserow
    component: baserow-backend
  name: baserow-backend-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    app: baserow-backend
    deploymentconfig: baserow-backend
status: {}
