apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: baserow
    component: baserow-backend
  name: baserow-backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
