apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    app: baserow
    app.kubernetes.io/part-of: baserow
    component: baserow-backend
  name: baserow-backend
spec:
  replicas: 1
  selector:
    app: baserow
    deploymentconfig: baserow-backend
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: baserow
        deploymentconfig: baserow-backend
    spec:
      containers:
        - image: ' '
          name: baserow-backend
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /backend
              name: baserow-backend-claim0
      restartPolicy: Always
      volumes:
        - name: baserow-backend-claim0
          persistentVolumeClaim:
            claimName: baserow-backend-claim0
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - baserow-backend
        from:
          kind: ImageStreamTag
          name: baserow-backend:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
