apiVersion: v1
kind: Service
metadata:
  labels:
    app: baserow
    component: baserow-backend
  name: baserow-backend
spec:
  ports:
    - name: "8000"
      port: 8000
  selector:
    app: baserow
    deploymentconfig: baserow-backend
