---
apiVersion: v1
kind: Template
parameters:
  - name: APP
    value: baserow
  - name: COMPONENT
    value: database
  - name: IMG_TAG
    value: latest
labels:
  app: ${APP}
  component: ${COMPONENT}
objects:
  - apiVersion: v1
    data:
      database-name: YmFzZXJvdw==
      database-password: YmFzZXJvdw==
      database-user: YmFzZXJvdw==
    kind: Secret
    metadata:
      labels:
        app: ${APP}
      name: ${APP}-${COMPONENT}
    type: Opaque
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: ${APP}
        component: ${APP}-${COMPONENT}
        template: postgresql-persistent-template
      name: ${APP}-${COMPONENT}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP}
        component: ${APP}-${COMPONENT}
        template: postgresql-persistent-template
      name: ${APP}-${COMPONENT}
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: ${APP}
        deploymentconfig: ${APP}-${COMPONENT}
      strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: ${APP}
            deploymentconfig: ${APP}-${COMPONENT}
        spec:
          containers:
            - env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: ${APP}-${COMPONENT}
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: ${APP}-${COMPONENT}
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: ${APP}-${COMPONENT}
              image: docker-registry.default.svc:5000/openshift/postgresql@sha256:094097e33f6d3cd498194ad7dc7bdb32f3d62b6a56ad8ae425770cd4050ad611
              imagePullPolicy: IfNotPresent
              livenessProbe:
                exec:
                  command:
                    - /usr/libexec/check-container
                    - --live
                failureThreshold: 3
                initialDelaySeconds: 120
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
              name: postgresql
              ports:
                - containerPort: 5432
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /usr/libexec/check-container
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 512Mi
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /var/lib/pgsql/data
                  name: ${APP}-${COMPONENT}
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: ${APP}-${COMPONENT}
              persistentVolumeClaim:
                claimName: ${APP}-${COMPONENT}
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - postgresql
            from:
              kind: ImageStreamTag
              name: postgresql:${IMG_TAG}
              namespace: openshift
          type: ImageChange
        - type: ConfigChange
    status:
      availableReplicas: 0
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      unavailableReplicas: 0
      updatedReplicas: 0
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP}
        component: ${APP}-${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      ports:
        - name: "5432"
          port: 5432
      selector:
        app: ${APP}
        deploymentconfig: ${APP}-${COMPONENT}
