apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: baserow
    component: baserow-db
    template: postgresql-persistent-template
  name: baserow-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
