apiVersion: v1
data:
  database-name: YmFzZXJvdw==
  database-password: YmFzZXJvdw==
  database-user: YmFzZXJvdw==
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: "{.data['database-name']}"
    template.openshift.io/expose-password: "{.data['database-password']}"
    template.openshift.io/expose-username: "{.data['database-user']}"
  creationTimestamp: null
  labels:
    template: postgresql-persistent-template
    template.openshift.io/template-instance-owner: 8418840b-2f9b-11eb-9613-0050568348cc
  name: baserow-db
type: Opaque
