apiVersion: v1
kind: Service
metadata:
  labels:
    app: baserow
    component: baserow-db
  name: baserow-db
spec:
  ports:
    - name: "5432"
      port: 5432
  selector:
    app: baserow
    deploymentconfig: baserow-db
