apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: baserow
    component: baserow-mjml
  name: baserow-mjml
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: docker.io/liminspace/mjml-tcpserver:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
