---
apiVersion: v1
kind: Template
parameters:
  - name: APP
    value: baserow
  - name: COMPONENT
    value: mjml
  - name: IMG_TAG
    value: latest
labels:
  app: ${APP}
  component: ${COMPONENT}
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP}
        component: ${APP}-${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      lookupPolicy:
        local: false
      tags:
        - from:
            kind: DockerImage
            name: docker.io/liminspace/mjml-tcpserver:${IMG_TAG}
          importPolicy: {}
          name: latest
          referencePolicy:
            type: ""
