---
apiVersion: v1
kind: Template
parameters:
  - name: APP
    value: baserow
  - name: COMPONENT
    value: mjml
  - name: IMG_SRC_REPO
    value: docker-remote.artifacts.developer.gov.bc.ca/liminspace/mjml-tcpserver
  - name: IMG_SRC_TAG
    value: "0.10"
labels:
  app: ${APP}
  component: ${COMPONENT}
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APP}-${COMPONENT}
    spec:
      tags:
        - from:
            kind: DockerImage
            name: ${IMG_SRC_REPO}
          importPolicy: {}
          name: ${IMG_SRC_TAG}
          referencePolicy:
            type: Source
