---
apiVersion: v1
kind: Template
parameters:
  - name: APP
    value: baserow
  - name: COMPONENT
    value: mjml
  - name: SRC_TAG
    value: "10"
  - name: SRC_NAMESPACE
    value: csnr-devops-lab-deploy
  - name: SRC_REGISTRY
    value: docker-registry.default.svc:5000
labels:
  app: ${APP}
  component: ${COMPONENT}
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP}
        component: ${APP}-${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      replicas: 1
      selector:
        app: ${APP}
        deploymentconfig: ${APP}-${COMPONENT}
      strategy:
        resources: {}
      template:
        metadata:
          labels:
            app: ${APP}
            deploymentconfig: ${APP}-${COMPONENT}
        spec:
          containers:
            - image: ${SRC_REGISTRY}/${SRC_NAMESPACE}/${APP}-${COMPONENT}:${SRC_TAG}
              imagePullPolicy: Always
              name: ${APP}-${COMPONENT}
              ports:
                - containerPort: 28101
              resources: {}
          restartPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP}-${COMPONENT}
            from:
              kind: ImageStreamTag
              name: ${APP}-${COMPONENT}:${SRC_TAG}
              namespace: ${SRC_NAMESPACE}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP}
        component: ${APP}-${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      ports:
        - name: "28101"
          port: 28101
          targetPort: 28101
      selector:
        app: ${APP}
        deploymentconfig: ${APP}-${COMPONENT}
