apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mjml
  name: mjml
spec:
  ports:
    - name: "28101"
      port: 28101
      targetPort: 28101
  selector:
    io.kompose.service: mjml
status:
  loadBalancer: {}
