apiVersion: v1
kind: Service
metadata:
  labels:
    app: baserow
    component: baserow-mjml
  name: baserow-mjml
spec:
  ports:
    - name: "28101"
      port: 28101
      targetPort: 28101
  selector:
    app: baserow
    deploymentconfig: baserow-mjml
