---
apiVersion: v1
kind: Template
labels:
  app: ${APP}
  component: ${COMPONENT}
parameters:
  - name: APP
    value: baserow
  - name: COMPONENT
    value: web-frontend
  - name: IMG_IS_TAG
    value: latest
  - name: IMG_SRC_TAG
    value: latest
  - name: SRC_GIT_URL
    value: https://gitlab.com/bramw/baserow.git
  - name: SRC_RELEASE
    value: 0.5.0
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${APP}-${COMPONENT}:${IMG_IS_TAG}
      resources:
        limits:
          memory: 4Gi
        requests:
          memory: 2Gi
      selector:
        app: ${APP}-${COMPONENT}
        deploymentconfig: ${APP}-${COMPONENT}
      source:
        dockerfile: |
          FROM node:10

          WORKDIR /web-frontend
          RUN git clone ${SRC_GIT_URL} -b ${SRC_RELEASE} /tmp/baserow && \
              cp -rT /tmp/baserow/web-frontend . && \
              rm -rf /tmp/baserow

          RUN apt-get update
          RUN apt-get -y install make curl gnupg2

          # Bug workaround (FATAL Vue packages version mismatch)
          RUN npm install vue-server-renderer@2.6.12 --save
          RUN npm install
          RUN npm run build

          RUN mkdir /.npm && \
              chown -R 1000870000:0 /.npm && \
              chmod -R 777 /web-frontend

          CMD npm run start

        type: Dockerfile
      strategy:
        dockerStrategy:
          from:
            kind: DockerImage
            name: node:${IMG_SRC_TAG}
        type: Docker
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
