apiVersion: v1
kind: Route
metadata:
  labels:
    app: baserow
    component: baserow-web-frontend
  name: baserow-web-frontend
spec:
  host: baserow-web-frontend-csnr-devops-lab-deploy.pathfinder.gov.bc.ca
  port:
    targetPort: "3000"
  to:
    kind: Service
    name: baserow-web-frontend
  tls:
    termination: edge
