apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web-frontend
  name: web-frontend
spec:
  replicas: 1
  selector:
    io.kompose.service: web-frontend
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/baserow_default: "true"
        io.kompose.service: web-frontend
    spec:
      containers:
        - image: ' '
          name: web-frontend
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /web-frontend
              name: web-frontend-claim0
      restartPolicy: Always
      volumes:
        - name: web-frontend-claim0
          persistentVolumeClaim:
            claimName: web-frontend-claim0
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - web-frontend
        from:
          kind: ImageStreamTag
          name: web-frontend:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
