apiVersion: v1
kind: Service
metadata:
  labels:
    app: baserow
    component: baserow-web-frontend
  name: baserow-web-frontend
spec:
  ports:
    - name: "3000"
      port: 3000
  selector:
    app: baserow
    deploymentconfig: baserow-web-frontend
