apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: baserow
    app.kubernetes.io/part-of: baserow
    component: baserow-web-frontend
    io.kompose.service: baserow-web-frontend-claim0
  name: baserow-web-frontend-claim0
spec:
  selector:
    app: baserow-web-frontend
    deploymentconfig: baserow-web-frontend
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
