---
apiVersion: v1
kind: Template
labels:
  app: ${APP}
  component: ${COMPONENT}
parameters:
  - name: APP
    value: baserow
  - name: COMPONENT
    value: web-frontend
  - name: PORT
    value: "3000"
  - name: IMG_IS_TAG
    value: latest
  - name: BACKEND_COMPONENT
    value: backend
  - name: BACKEND_PORT
    value: "8000"
  - name: NAMESPACE
    value: csnr-devops-lab-deploy
  - name: DOMAIN
    value: pathfinder.gov.bc.ca
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      replicas: 1
      selector:
        app: ${APP}
        deploymentconfig: ${APP}-${COMPONENT}
      strategy:
        resources: {}
      template:
        metadata:
          labels:
            app: ${APP}
            deploymentconfig: ${APP}-${COMPONENT}
        spec:
          containers:
            - env:
                - name: PUBLIC_BACKEND_URL
                  value: https://${APP}-${BACKEND_COMPONENT}-${NAMESPACE}.${DOMAIN}
                - name: PRIVATE_BACKEND_URL
                  value: http://${APP}-${BACKEND_COMPONENT}:${BACKEND_PORT}
                - name: PUBLIC_WEB_FRONTEND_URL
                  value: https://${APP}-${COMPONENT}-${NAMESPACE}.${DOMAIN}
              image: " "
              name: ${APP}-${COMPONENT}
              ports:
                - containerPort: ${{PORT}}
              resources: {}
          restartPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP}-${COMPONENT}
            from:
              kind: ImageStreamTag
              name: ${APP}-${COMPONENT}:${IMG_IS_TAG}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      ports:
        - name: ${PORT}
          port: ${{PORT}}
      selector:
        app: ${APP}
        deploymentconfig: ${APP}-${COMPONENT}
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP}
        component: ${COMPONENT}
      name: ${APP}-${COMPONENT}
    spec:
      host: ${APP}-${COMPONENT}-${NAMESPACE}.${DOMAIN}
      port:
        targetPort: ${PORT}
      to:
        kind: Service
        name: ${APP}-${COMPONENT}
      tls:
        termination: edge
